server:
  port: 8080

spring:
  application:
    name: webtoon-review
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      routes:
        - id: user-register-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users
            - Method=POST
        - id: user-login-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/login
            - Method=POST
        - id: webtoon-service-get-post
          uri: http://localhost:8081
          predicates:
            - Path=/api/webtoons/**
            - Method=GET,POST
          filters:
            - name: UserRateLimiterGatewayFilter
              args:
                rateLimitIntervalInSeconds: 1
                requestLimitPerInterval: 5
            - name: AuthorizationGatewayFilter
        - id: webtoon-list-get-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/webtoons
            - Method=GET
          filters:
            - name: UserRateLimiterGatewayFilter
              args:
                rateLimitIntervalInSeconds: 1
                requestLimitPerInterval: 5
            - name: AuthorizationGatewayFilter
      default-filters:
        - name: IpRateLimiterGatewayFilter
          args:
            rateLimitIntervalInSeconds: 1
            requestLimitPerInterval: 5
