spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_DATABASE_HOST}:${MYSQL_DATABASE_PORT}/${MYSQL_DATABASE_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}


  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

server:
  ssl:
    enabled: true
    key-store-type: ${SSL_TYPE}
    key-store: classpath:${SSL_PATH}
    key-store-password: ${SSL_PASSWORD}

jwt:
  key: ${JWT_KEY}
